name: build and release
on:
  workflow_dispatch:  # Allow manual trigger
  watch:
    types: [started]  # Triggers when upstream repo gets a new star (proxy for activity)
  release:
    types: [published]  # Triggers when upstream creates a new release
  push:
    tags:
      - '*'  # Sync to GitLab when a tag is pushed

jobs:
  sync:
    runs-on: ubuntu-latest
    # Only run if the event is from the upstream repository or manual trigger
    if: github.repository != 'orthanc-server/orthanc-explorer-2' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0  # Fetch all history for proper syncing

      - name: Configure Git
        run: |
          git config --global user.name "badrinteractive (GitHub Actions)"
          git config --global user.email "admin@badr-interactive.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/orthanc-server/orthanc-explorer-2.git

      - name: Fetch upstream changes
        run: |
          git fetch upstream --tags

      - name: Merge upstream changes
        run: |
          git merge upstream/master --no-edit || {
            echo "Merge conflict detected. Resetting to upstream master..."
            git reset --hard upstream/master
          }
          git push origin master

      - name: Trigger GitLab sync job
        if: ${{ success() }}
        run: |
          echo "Triggering GitLab sync job..."

  gitlab_sync:
    needs: [sync]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch from GitHub
        uses: actions/checkout@v2
        with:
          ref: 'master'
          fetch-depth: 0  # Fetch all history for proper syncing

      - name: Set up Git
        run: |
          git config --global user.name "badrinteractive (GitHub Actions)"
          git config --global user.email "admin@badr-interactive.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.badr.co.id/badr-interactive/orthanc-explorer-2.git

      - name: Push to GitLab (branch "github")
        run: |
          # Force push the current master branch to GitLab's github branch
          git push -f gitlab HEAD:github
